version: "2"
services:
  varnish:
    build:
      context: ./CachingServer/
    volumes:
      - ./CachingServer/default.vcl:/usr/local/etc/varnish/default.vcl
    ports:
    - "8081:80"
    depends_on:
    - webserver1
  webserver1:
    container_name: webserver1
    build:
      context: ./WebServer/
    environment:
      PORT: "3002:80"